# Generated by Django 5.1.7 on 2025-03-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofiles",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="userprofiles",
            name="address_line_2",
        ),
        migrations.AddField(
            model_name="userprofiles",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
